#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
if [ -h "$SOURCE" ]; then
  SOURCE="$(readlink "$SOURCE")"
fi
DIR="$(dirname $SOURCE)"

SCRIPT=$DIR/../target/universal/stage/bin/race-odin
 

if [ -x $SCRIPT ]; then
  $SCRIPT $@
else
  echo "script $SCRIPT does not exist, run sbt stage"
fi

